<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>6a25231a-f8ad-4871-8a66-972f99881c57</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" Version="9.7.0" />
        <PackageReference Include="Microsoft.SemanticKernel" Version="1.71.0" />
        <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.71.0" />
        <PackageReference Include="Microsoft.SemanticKernel.Connectors.InMemory" Version="1.71.0-preview" />
        <PackageReference Include="Microsoft.SemanticKernel.PromptTemplates.Handlebars" Version="1.68.0" />
        <PackageReference Include="ClosedXML" Version="0.104.2" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Samples\MyAgents\IncidentTriageAgent\Prompts\IncidentTriagePrompt.yaml" />
        <EmbeddedResource Include="Samples\MyAgents\IncidentTriageAgent\Prompts\IncidentTriagePrompt.yaml" />
        <None Remove="Samples\MyAgents\SummarizationAgent\Prompts\SummarizationPrompt.yaml" />
        <EmbeddedResource Include="Samples\MyAgents\SummarizationAgent\Prompts\SummarizationPrompt.yaml" />
    <None Remove="Samples\MyAgents\MobilityFormAgent\Prompts\MobilityFormPrompt.yaml" />
    <None Remove="Samples\MyAgents\MobilityFormAgentClean\Prompts\MobilityFormPromptClean.yaml" />
    <EmbeddedResource Include="Samples\MyAgents\MobilityFormAgentClean\Prompts\MobilityFormPromptClean.yaml" />

    </ItemGroup>


    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

   


    <ItemGroup>
        <None Update="Samples\MobilityAssistant\BaselineForm.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
